name: auto-release
on:
  push:
    branches: [ main ]

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }

      - name: Find new release file
        id: scan
        run: |
          set -e
          ADDED=$(git diff --name-status HEAD~1..HEAD | awk '$1=="A"{print $2}')
          FILE=$(echo "$ADDED" | grep -E '^Verter_v[0-9]+\.[0-9]+\.[0-9]+\.user\.js$' || true)
          if [ -z "$FILE" ]; then echo "version=" >> $GITHUB_OUTPUT; exit 0; fi
          VER=$(echo "$FILE" | sed -E 's/^Verter_v([0-9]+\.[0-9]+\.[0-9]+)\.user\.js$/\1/')
          echo "file=$FILE"    >> $GITHUB_OUTPUT
          echo "version=$VER"  >> $GITHUB_OUTPUT

      - name: Stop if no release file
        if: steps.scan.outputs.version == ''
        run: echo "No new Verter_v*.user.js — skip."

      - name: Create tag
        if: steps.scan.outputs.version != ''
        run: |
          git tag "v${{ steps.scan.outputs.version }}" || true
          git push origin "v${{ steps.scan.outputs.version }}" || true

      - name: Create GitHub Release
        if: steps.scan.outputs.version != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.scan.outputs.version }}"
          name: "Verter v${{ steps.scan.outputs.version }}"
          body: |
            Auto-release from merged PR.
            Source file: ${{ steps.scan.outputs.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
